server:
  port: 8079
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/revolusion_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  token:
    expireDays: 7
    secretKey: '03d2430e18744da8db2b8dbd64a64977be5c1a7f06d52197c9b8113a3b552c69'

  code:
    attempt: 3
    expireMinute: 180000

  java-mail:
    verification-url: http://localhost:${server.port}/auth/verify-email
    reset-password: http://localhost:${server.port}/auth/verify-reset-password

  attachment:
    base-path: C:\Users\User\Desktop\projects\revolusion-demo\files